express-rate-limit/express-rate-limit

- README.md
- lib/express-rate-limit.js
- test/test.js
Custom message when max connections are reached - updated: source code, test & docs
> Custom message when max connections are reached

- README.md
- lib/express-rate-limit.js
- test/test.js
Dear Sir,
In this pull request I have added a key generation function which allows the users to implement custom keys, not only users' IPs.
Thanks!
> Custom condition

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit.js
Added the possibility to show request limit and remaining request
available in HTTP response header
To Do:
- Add reset timer in header
> RateLimit Header

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit.js
This is a copy of https://github.com/nfriedly/express-rate-limit/pull/29 with suggestions made so this can get merged in.
Made sure to add in tests and appropriate documentation.
Please let me know if there is something missing or tests not done appropriately and will be happy to fix.
Thanks
> Add in the ability to skip rate limiting with a custom function

- README.md
- lib/express-rate-limit.js
Hi,
I needed an event to log infos when an user reach the limit and I didn't want to override default handler method only for that. This PR add a function to this use-case.
Thanks !
> Feature events

- lib/memory-store.js
Fixed comment on the API that seemed to be misplaced.
> Fix clarification comment position

- README.md
I created a [memcached-store](https://github.com/linyows/rate-limit-memcached) so please add it to README. Thank you for the express-rate-limit of greate software.
> Add memcached-store to README.md

- README.md
- lib/express-rate-limit.js
for frequent requests with some of password ( to avoid bruteforce)
>  Added ability to skip successful requests

- README.md
New storage implementation was added, here is a link ;)
> Add link to mongo store to readme

- index.d.ts
I think this needs to be improved more, if anyone wants to review the PR and check it out their local branch that would be great
> first draft for the types for express rate limiter

- index.d.ts
We the function RateLimit as the default export
> Fix bug with TypeScript support

- index.d.ts
just updates the definitions file with a typescript syntax fix..
> :bug: fixes Ratelimit interface to use valid typescript

- .editorconfig
- README.md
- lib/express-rate-limit.ts
- package-lock.json
- package.json
- test/tsconfig.json
A couple of improvements on top of the typescript conversion.
- Since you noted that the stores do not have to return the resetTime, I changed the type on the increment callback as well
- Made all of the properties on the interfaces read only, since they are handled as such anyway
- Created a helper function for getting the current request's rate limit, since it's always a bit difficult to access those added request properties in ts
- Added a bit of extra support for tests written in typescript
> Typescript improvements

- lib/memory-store.js
> Refactoring cleanup

- LICENSE
- README.md
- lib/express-rate-limit.js
- test/express-rate-limit-test.js
Allows `skip` function to be asynchronous and fixes an issue mentioned in #184
> Allows asynchronous skip functions

- lib/express-rate-limit.js
https://github.com/nfriedly/express-rate-limit/issues/214
> allow handler to access options

- package.json
- readme.md
- source/index.ts
- test/external/imports/default-import/js-cjs/source/app.js
- test/external/imports/default-import/js-esm/source/app.js
- test/external/imports/default-import/ts-cjs/source/app.ts
- test/external/imports/default-import/ts-esm/source/app.ts
- test/external/imports/named-import/js-cjs/source/app.js
- test/external/imports/named-import/js-esm/source/app.js
- test/external/imports/named-import/ts-cjs/source/app.ts
- test/external/imports/named-import/ts-esm/source/app.ts
- Closes #289
- Added a named export for the `MemoryStore` class.
> feat: add named export for memory store

- .github/workflows/ci.yaml
- package.json
- test/external/imports/default-import/ts-cjs/tsconfig.json
- test/external/imports/default-import/ts-esm/tsconfig.json
- test/external/imports/named-import/ts-cjs/tsconfig.json
- test/external/imports/named-import/ts-esm/tsconfig.json
- test/external/stores/tsconfig.json
- Fixes #278 
- Changes the build target to `es2019` so that ESBuild outputs code that can run with Node 12.
- Changes minimum Node version to 12.9.0.
None
> meta: support node 12

- .github/workflows/ci.yaml
--
- Runs Lint and Publish steps of CI on Node 18.
- Added Node 18 to version matrix for Test steps too.
--
> meta: run ci on node 18

- package-lock.json
- package.json
- test/external/imports/default-import/js-cjs/package.json
- test/external/imports/default-import/js-esm/package.json
- test/external/imports/default-import/ts-cjs/package.json
- test/external/imports/default-import/ts-cjs/tsconfig.json
- test/external/imports/default-import/ts-esm/package.json
- test/external/imports/named-import/js-cjs/package.json
- test/external/imports/named-import/js-esm/package.json
- test/external/imports/named-import/ts-cjs/package.json
- test/external/imports/named-import/ts-cjs/source/index.ts
- test/external/imports/named-import/ts-cjs/tsconfig.json
- test/external/imports/named-import/ts-esm/package.json
- test/external/imports/named-import/ts-esm/source/index.ts
- test/external/run-all-tests
- test/external/stores/package.json
- Fixes #355
- Bumps test project dependencies.
- Changes `export` field in package.json to export different `.d.ts` files for CommonJS and ESM projects.
> fix(ts): export diff type files for cjs and esm

- contributing.md
Just a minor rewording. I think it's a little more clear, although I'm not sure it's a big improvement.
> docs: tweak wording around linting/testing in contributing.md

- readme.md
See https://github.com/express-rate-limit/express-rate-limit/discussions/399#discussioncomment-7012726
> docs: Added rate-limit-postgresql reference in readme.

- readme.md
Also, explain the relevant difference. Not sure about the wording, though.
> Memcached is a modern store now 🎉

- docs/overview.mdx
- docs/quickstart/usage.mdx
- readme.md
Link to ratelimit-header-parser & tweak the usage intro.
I may end up adding a couple more, but I think this is good to merge in as-is.
> docs: minor tweaks

- docs/overview.mdx
Hi @gamemaker1 @nfriedly - would it be possible to make this quick change to the sponsor link
> Update overview.mdx sponsor link

- readme.md
I've been thinking that it would be good to have a quick overview of the supported configuration options in the readme. This lists them with types, a short description, and a link to the full docs for each one. 
I considered adding more complete signatures for the options that accept functions, but I felt like it was a bit too much.
I'm a bit on the fence about the Thank You section, but I think it's probably a good thing overall.
What do you think @gamemaker1 ?
This is the last bit I was thinking I wanted to merge in before putting out a new semver-minor release. (I suppose we also need to update the changelog...)
> docs: add Configuration & Thank You sections to readme

- docs/quickstart/usage.mdx
This calls it out as not officially supported, but provides enough info to get someone started if they wanted to do it anyways.
Fixes https://github.com/express-rate-limit/rate-limit-postgresql/issues/36
@gamemaker1 what do you think of my [suggestion of an official next.js support package](https://github.com/express-rate-limit/rate-limit-postgresql/issues/36#issuecomment-2688541101)?
> Next.js usage note in docs

- test/library/memory-store-test.ts
Added a unit test for resetKey in MemoryStore.
> Add unit test for resetKey method in MemoryStore

- source/headers.ts
- source/validations.ts
- test/library/options-test.ts
> fix: type of DraftHeadersVersion
