- .travis.yml
- README.md
- lib/express-rate-limit.js
- package.json
- test/test.js
The handler defaults to a function which receives a response object of Express
and negociates the content of the response based on the Contetn-Type header of the request.
Files changed:
modified:   README.md
modified:   lib/express-rate-limit.js
> Add a handler option

- README.md
- lib/express-rate-limit.js
- lib/memory-store.js
- test/express-rate-limit.js
- test/memory-store.js
I really liked the simplicity of the package, but I wanted to extend it for use with other stores.
I've abstracted out the Memory Store into a model that can now be plugged in as need be with other databases. The only requirements of any other store is that it must provide the following methods:
- `incr`: This method must accept a key, and a callback, the key will be incremented and the new value returned in the callback, along with any error that occurred.
- `resetKey`: This method resets the key indicated in an atomic operation
- `resetAll` (optional): This method resets all the keys stored for the rate limiting middleware
Would love for any feedback :)
> Abstracted backend store out from RateLimit

- lib/express-rate-limit.js
Current limit helps to do deep analysis in sudden spike of request in the handler.
> Passing current limit as part of rateLimit payload

- lib/memory-store.js
- test/memory-store.js
We run integration tests in Electron where we were see a different return value from `setInterval()` than in pure node causing `unset` to be undefined.
> Runs in electron where setInterval() returns only a number

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit.js
Adds basic support for the `Retry-After` header
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
I say "basic" as all I have done is return the windowMs in seconds. It would be preferable to actually return how long until the current window will elapse but I might leave that to you @nfriedly :)
> Retry-After header

- README.md
The link to the Redis store is only working on while viewing the docs on github.  
While viewing on npmjs.com clicking the link directs me to
https://github.com/nfriedly/express-rate-limit/blob/HEAD/%5BRedis%5D(http:/redis.io/)-backed%20store,%20more%20suitable%20for%20large%20or%20demanding%20deployments.
which is a 404 Page not found for me.
Also the redis link is missing from the lower store list on npm (not on github)
see the below screenshot
I fixed the links in both places.
> Fixed store links

- lib/express-rate-limit.js
Closes #94.
If this is the appropriate way to resolve, it ought to be back-ported to express-rate-limit v2 as well.
> Fix Date response header format

- lib/express-rate-limit.js
This bug rose from https://github.com/nfriedly/express-rate-limit/releases/tag/v3.2.0 where max can now be a function (which is extremely useful btw so thanks!).
Please merge at your earliest convenience so that we can start using max as a function.
Thanks!
> Fixed NaN remaining when max is a function

- README.md
`strict-rate-limiter`is outdated and has not been supported for 3 years. 
`rate-limiter-flexible` is recognized by expressjs community and listed in official docs as part of best security practices
> Update: alternate limiters list

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit-test.js
Right now in case request was terminated by client side, or in case of something very unpredictable happens and response will trigger `error` event counter doesn't decrement with options `skipFailedRequests` and `skipSuccessfulRequests` set.
Added counter decrement on response events `close` and `error`. This would happen only if option `skipFailedRequests` is set.
> add close and error event handlers for response, actualize readme

- lib/express-rate-limit.js
- test/express-rate-limit-test.js
Since node v11.x.x behaviour of response `close` event changed and now it's triggered always, whether `response.end()` was called or not. So i added `res.finished` check in close event handler and also added some tests.
> fix response close event for node v11.x.x

- index.d.ts
- package.json
The `send` function on Express.Request is typed as accepting `any` value. Since the documentation states the `message` option will be directly passed to `send`, it makes sense to have the same type here.
> Fix type of message to match Request.send

- package.json
Just one more thing in the way of the typings, they aren't getting included in the package because of the files prop in package.json. This fixes that
> Include typescript typings in npm package

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit-test.js
For #168 
* Added new option `draft_polli_ratelimit_headers` set to `false`.
* Added the set of new headers `RateLimit-Limit`, `RateLimit-Remaining` and `RateLimit-Reset`.
* Added *draft_polli_ratelimit_headers* in Docs.
> Config for RateLimit standardization headers 

- lib/express-rate-limit.js
- test/express-rate-limit-test.js
Allow express to handle exceptions with default error handler. Now, we can throw an exception into `handler` callback if limits reached.
@see https://expressjs.com/en/guide/error-handling.html#the-default-error-handler
> Handle exceptions

- lib/express-rate-limit.js
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString
Interestingly, .toGMTString is actually already .toUTCString in node v14
> Change Date.toGMTString to Date.toUTCString due to deprecation

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit-test.js
This PR adds ability to decide if request was successful (and as the result should be skipped) manually, based on request and/or response.
I had a use-case when comparison against `response.statusCode` wasn't enough, because application always responds with redirects to static pages (3xx) if error happened
Hope, this feature could be useful for community 🙌 
_Backward compatibility is saved_
> Ability to manually decide if request was successful

- README.md
- lib/express-rate-limit.js
- test/express-rate-limit-test.js
Allow to rename the req.rateLimit parameter. Useful if using more than one rateLimiter with different keys.
> add option to allow  custom param name added to req

- package.json
- test/external/imports/js-cjs/package.json
- test/external/imports/js-esm/package.json
- test/external/imports/ts-cjs/package.json
- test/external/imports/ts-esm/package.json
- test/external/run-all-tests
- Fixes #277
- Run `eslint` as part of the import tests too.
- Add the `main` and `module` fields to `package.json` so ESLint does not complain
> meta: add `main` field to `package.json` and run eslint tests along with import tests

- test/external/imports/js-cjs/package.json
- test/external/imports/js-esm/package.json
- test/external/imports/ts-cjs/package.json
- test/external/imports/ts-esm/package.json
- test/external/run-all-tests
- test/external/stores/package.json
Fixes https://github.com/nfriedly/express-rate-limit/pull/282#discussion_r779520826
- Instead of building a `.tgz` file and installing it in all external tests, install the project folder directly in the external tests.
> meta: soft link all external tests to the project folder

- package-lock.json
- package.json
- readme.md
- source/lib.ts
- source/memory-store.ts
- source/types.ts
- Fixes #287
- Deprecates `onLimitReached`, as v6.0.0 was supposed to do.
- Bumps development dependencies (minor/patch changes only).
- Fixes inconsistencies between the readme and `source/types.ts`.
> fix: deprecate `onLimitReached`, reword documentation

- source/lib.ts
- source/types.ts
Closes #290
This PR changes how options are merged with the defaults. At the moment, passing
```js
{ windowMs: undefined }
```
as an option, will result in `windowMs` being set to undefined, rather than falling back to the default of `60000ms`. This is a bit counterintuitive, as most APIs in JS do not differentiate between a property not existing and a property being undefined. This is a consequence of the spread operator being used, though.
Added a new private function that omits the options, and is called inside `parseOptions`.
TypeScript **really** sucks at dealing with object mutation like this. I have had to add a `@ts-expect-error` and `eslint-disable-next-line` inside the function that mutates the object. I spent about 15 minutes trying to come up with a neater way to mutate the …
> fix: use default value for option when `undefined` is passed

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- test/external/run-all-tests
This PR will resolve the peer dependency error fix for express v5
> meta: add express 5 as peer dependency

- readme.md
- source/lib.ts
- source/types.ts
- test/library/middleware-test.ts
Allow for manual response to ratelimit by function message.
> feat: allow the `message` option to be a function

- package.json
- Fixes #319 
Fixes types missing in ESM monorepos
Add ``types`` to module exports: https://nodejs.org/api/packages.html#community-conditions-definitions
> fix types missing in ESM monorepos

- source/memory-store.ts
- source/types.ts
- test/external/imports/default-import/ts-cjs/source/app.ts
- test/external/imports/default-import/ts-cjs/source/index.ts
- test/external/imports/default-import/ts-cjs/test/server-test.ts
- test/external/imports/default-import/ts-esm/source/app.ts
- test/external/imports/default-import/ts-esm/source/index.ts
- test/external/imports/default-import/ts-esm/test/server-test.ts
- test/external/imports/named-import/ts-cjs/source/app.ts
- test/external/imports/named-import/ts-cjs/test/server-test.ts
- test/external/imports/named-import/ts-esm/source/app.ts
- test/external/imports/named-import/ts-esm/test/server-test.ts
- test/library/memory-store-test.ts
Fixes https://github.com/nfriedly/express-rate-limit/issues/320
Added `MemoryStore.shutdown` which clears the timer and allows applications to completely stop a running instance of MemoryStore.
> Added MemoryStore shutdown method

- package-lock.json
- package.json
This is a potential fix for #360 and might be a good idea regardless, as dts-bundle-gen v8.0.0 appears to have [dropped support for typescript <5](https://github.com/timocov/dts-bundle-generator/pull/240). (I should have scrutinized this more closely before including it in a point release...)
Additionally, the types it generates vary slightly depending on which version of typescript is used, so I rolled that back to 4.x as well.
express-rate-limit@6.7.0 used
* typescript@4.8.4
* dts-bundle-generator@7.0.0
express-rate-limit@6.7.1 used
* typescript@5.1.6
* dts-bundle-generator@8.0.1
This PR has 
* typescript@4.9.5
* dts-bundle-generator@7.2.0. 
If that doesn't solve the issue, I may revert all the way back to the exact versions used for 6.7.0.
> Revert typescript to 4.x and dts-bundle-generator to 7.x

- source/lib.ts
- source/memory-store.ts
- source/types.ts
- source/validations.ts
- test/library/validation-test.ts
This implements the idea discussed in https://github.com/express-rate-limit/express-rate-limit/discussions/356#discussioncomment-6551246 to check for cases of double-counting a single request.
There's probably some situations that this doesn't account for, but I tried to cover the main ones.
We'll want to update the PreciseMemoryStore and set it to `localKeys = true` after merging this. (Although, I'm not sure that `localKeys` is the name I want to settle on.)
* https://github.com/express-rate-limit/express-rate-limit/issues/362
* Possibly https://github.com/express-rate-limit/express-rate-limit/issues/354
- New validation check looking for double-couting of requests
🤷‍♂️ 
> feat: validation check for double-counting hits for a single request

- source/validations.ts
I also cleaned up the text a bit since the error code and the fact that it's coming from express-rate-limit are both fairly apparent
* https://github.com/express-rate-limit/express-rate-limit/issues/363
* https://github.com/express-rate-limit/express-rate-limit/discussions/356#discussioncomment-6551094
* https://github.com/express-rate-limit/express-rate-limit/pull/358
This fixes the mistake that caused the help URL to be removed from ValidationError messages. 
Additionally, it adds help a property on the object with the URL, for cases like #363 where the text isn't wrapped around.
I also tweaked the wording to remove redundant info and get to the point more quickly (although this redundant info was never actually shown because of the aforementioned mistake).
Previously errors looked like …
> fix: include url in `ValidationError`

- readme.md
And rework alternate rate limiters section
Should help to address some of the confusion evidenced in https://github.com/express-rate-limit/express-rate-limit/issues/366 and other tickets
Needs formatting because I just did the editing in github's ui
> doc: add use-cases section to readme

- source/lib.ts
- source/validations.ts
- test/library/validation-test.ts
Checks that the value is a positive integer. Would have helped with https://github.com/express-rate-limit/express-rate-limit/issues/353
todo:
> feat: validate `totalHits` value returned from store

- source/lib.ts
- source/types.ts
- source/validations.ts
- test/library/options-test.ts
Once this PR is merged, setting the `onLimitReached` and `draft_polli_ratelimit_headers` option will have no effect, apart from triggering a `ChangeWarning` validation error.
---
This is a breaking change, and should be merged as part of v7.
> chore: drop deprecated options

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- readme.md
This PR excludes node 14 from the CI, and bumps the typescript build target to `es2022`. 
---
This is a breaking change, and should be merged as part of v7.
> build: drop node 14

- readme.md
- source/lib.ts
- test/library/middleware-test.ts
This PR fixes #259. Once this PR is merged, setting the `max` option to zero will 'block' all requests to that endpoint.
---
This is a breaking change, and should be merged as part of v7.
> fix!: `max: 0` should rate limits all requests

- readme.md
- source/memory-store.ts
- test/library/memory-store-test.ts
- tsconfig.json
I've been thinking about how to make the MemoryStore have per-user reset times and still only a single global timer (like `precise-memory-rate-limit`), but *not* have to iterate through all known clients to remove expired ones (unlike `precise-memory-rate-limit`).
I came up with the idea for a previous and current set of clients, where we could pull active ones forward from previous to current, and then at the end of the time window, just blow away the previous, move the current to previous, and create a new current set.
I then refined it a bit to perform less allocations (and by extension, need less garbage collection) by merely swapping previous and current, and then moving the leftover clients from the old previous to a client pool. With an appropriately sized pool, it should be able …
> feat!: improve `MemoryStore`

- .gitignore
- jest.config.json
- package.json
Per https://jestjs.io/docs/configuration moving the jest config to `jest.cnfig.json`  allows it to be automatically discovered. This in turn makes the jest plugin for vs code "just work" (presumably other editors too), allowing me to easily run or debug individual tests.
I also cleaned up the command line to execute the tests, because I don't think we need any of those flags any more. 
Finally, I added the various external tests package-lock.json's to the .gitignore because they started showing up for some reason.
> chore: move jest config to standard location

- source/lib.ts
- source/memory-store.ts
- source/types.ts
- test/external/imports/default-import/ts-cjs/source/app.ts
- test/external/imports/default-import/ts-esm/source/app.ts
- test/external/imports/named-import/ts-cjs/source/app.ts
- test/external/imports/named-import/ts-esm/source/app.ts
- test/library/headers-test.ts
- test/library/memory-store-test.ts
- test/library/middleware-test.ts
- test/library/options-test.ts
- The function is also bound to the middleware so it can be called externally.
---
This PR fixes #389. The tests are currently failing since the external stores do not yet have the `fetchKey` function.
> feat: add `get` method to the `Store` interface

- source/lib.ts
- source/types.ts
- test/library/headers-test.ts
- test/library/middleware-test.ts
- This PR implements https://github.com/express-rate-limit/express-rate-limit/discussions/372#discussioncomment-6915685.
---
We should probably merge this in v7.
> fix: rename current to used, while still supporting current

- source/types.ts
- source/validations.ts
- test/library/validation-test.ts
This makes prefix an optional property on the store Interface (memcached and redis already use it), and then if set, prepends it to keys for the singleCount validation.
Fixes #395 (see #393)
> fix: consider store prefix in `singleCount` validation check

- readme.md
- source/lib.ts
- source/types.ts
- source/validations.ts
- test/library/middleware-test.ts
- test/library/validation-test.ts
This allows the `validate` option to be set to an object with keys for specific validation checks and boolean values to enable or disable the check. There is also a special `default` key that is used as the fallback value for unset keys. It defaults to `true`. 
It ended up being a kinda big change, but it also fixed the annoyance I had of needing to call `wrap()` inside of each validation check - they're now wrapped automatically - without using decorators!
Todo:
* This should wait until after v7 is published and/or clarify that v7.0.0 or newer is required for this feature.
* See https://github.com/express-rate-limit/express-rate-limit/wiki/Error-Codes#err_erl_unknown_validation
Should unblock https://github.com/express-rate-limit/express-slow-down/pull/43
Tip: review  with white space …
> Allow specific validations to be enabled or disabled

- source/types.ts
- test/external/stores/package.json
- test/external/stores/pnpm-lock.yaml
Restores `IncrementResponse ` as an alias of `ClientRateLimitInfo`
fixes https://github.com/express-rate-limit/rate-limit-redis/pull/192 (hopefully)
> fix: restore IncrementResponse type

- readme.md
I'm not sure I like the wording of the usage section now, what do you think?
> Add cluster-memory-store & call it out in usage section

- docs/mint.json
- package.json
I added this, but it doesn't seem to actually work. The server starts, but then it just hangs. I left it running overnight last night, and there was an error, I think it was something about a recursive symlink with express-rate-limit trying to load itself from the node_modules folder, but I accidentally lost the the full error message. I have the command running again, hoping to get it to print the error message.
> chore: add npm run docs command, remove docs/ prefix from urls

- package.json
Loosen up the peer dependencies to allow express 5 beta with npm's newer peer dependency resolution method.
Fixes https://github.com/express-rate-limit/express-rate-limit/issues/415 (hopefully)
> chore: loosen peer dependencies

- source/headers.ts
> fix: Ratelimit headers empty while running on Bun v1.0.x #418

- docs/guides/contributing.mdx
- docs/mint.json
- docs/quickstart/installation.mdx
- docs/reference/changelog.mdx
- package.json
Also removed the changelog and some other files from what gets published to npm. I think it's pretty rare for users to look in `node_modules` for documentation (especially for something like this that's designed for online use), and npm automatically includes the bits it needs (like the readme & package.json), so we don't need to specify those. 
It won't make a huge difference in file size, but multiplied by millions of downloads per week, it starts to add up to something significant.
(I originally noticed that we had a [broken link to docs/changelog.md](https://github.com/express-rate-limit/express-rate-limit/blob/v7.1.4/docs/quickstart/installation.mdx#L54) so I fixed that and some other broken links and pushed the fix to `main` right away, but then I thought it probably would make …
> chore: move changelog to docs folder/mintlify

- .github/workflows/ci.yaml
* Affects https://github.com/express-rate-limit/express-rate-limit/releases pages
* Assume directing devs/users to offsite area instead of [current dev location](https://github.com/express-rate-limit/express-rate-limit/blob/main/docs/reference/changelog.mdx)
Post #420
> fix: ci generation config of the url for changelog

- source/lib.ts
- test/library/middleware-test.ts
Fixes https://github.com/express-rate-limit/express-rate-limit/issues/425
The added test case fails on `main` but succeeds on this branch.
> Bugfix: requestWasSuccessful usage doesn't support returning a Promise

- docs/mint.json
- docs/overview.mdx
- docs/quickstart/usage.mdx
- docs/reference/configuration.mdx
- docs/reference/error-codes.mdx
- docs/reference/stores.mdx
- readme.md
This moves the list of stores from the bottom of the Configuration page to a new Data Stores page, and makes a few other changes to make it a little more prominent.
Closes #432
> docs: Create Data Stores documentation page

- docs/reference/configuration.mdx
- docs/reference/error-codes.mdx
- source/lib.ts
- source/validations.ts
- test/library/validation-test.ts
This is one of the ideas I wrote down on https://github.com/express-rate-limit/express-rate-limit/discussions/436 - it seems to work but I'm not yet certain I want to go with it. Also, I think it needs a better name than 'middleware'.
> Check for instance creation while handling a request

- docs/guides/creating-a-store.mdx
A couple of updates to the [creating a store guide](https://express-rate-limit.mintlify.app/guides/creating-a-store):
* call out `prefix` and `localKeys` fields
* make the sample code block wider
The second part required removing some of the formatting. It honestly looked nicer before, but I think this is more functional, because you don't have to scroll left-and-right as much to read the example code.
I also looked for a way to have the sample code in it's own standalone .ts and .js files, but couldn't figure out a way to do that and automatically import them into the document, and I think having example code in this document is more valuable. Reducing the level of indentation at least helped.
Context: https://github.com/express-rate-limit/express-rate-limit/discussions/442#discussioncomm …
> docs: update the create-a-store guide

- readme.md
This is just a readme update; I noticed on https://www.npmjs.com/package/express-rate-limit?activeTab=readme that the readme for filing an issue was sending to a 404 when I was checking out the package.
> fix: update readme to reflect current new issue

- docs/reference/changelog.mdx
- docs/reference/configuration.mdx
- docs/reference/error-codes.mdx
- package-lock.json
- source/lib.ts
- source/validations.ts
- test/library/middleware-test.ts
- test/library/validation-test.ts
This checks for cases like https://github.com/express-rate-limit/express-rate-limit/discussions/457 where a single Store instance is shared across multiple rate limiter instances.
I saw there was an unrelated formatting change to the one test, so I updated my node modules and got a vulnerability warning, so I went ahead and fixed that too.
Example error messages:
> ValidationError: A Store instance must not be shared across multiple rate limiters. Create a new instance of MemoryStore for each limiter instead. See https://express-rate-limit.github.io/ERR_ERL_STORE_REUSE/ for more information.
Example for a store that doesn't have `localKeys` set:
> ValidationError: A Store instance must not be shared across multiple rate limiters. Create a new instance of ClusterMemoryStoreWorker (with a …
> feat: storePerLimiter validation check

- docs/reference/changelog.mdx
- docs/reference/configuration.mdx
- readme.md
- source/lib.ts
- source/types.ts
- test/library/middleware-test.ts
I don't know why github closed #447 and won't let me re-open it, but I just gave up and recreated the PR here.
This PR:
* replaces #447 
* closes https://github.com/express-rate-limit/rate-limit-redis/pull/193
* fixes https://github.com/express-rate-limit/rate-limit-redis/issues/190
* fixes https://github.com/express-rate-limit/rate-limit-redis/issues/72
Original description below:
---
This PR adds the parameter passOnStoreError to allow requests if the store is not available.
For instance, if using Redis and the Redis server disconnects, the request will still pass.
This feature can be important for HA issues.
> feat: Added passOnStoreError to skip rate limitter if the store is not available (#447)

- docs/guides/troubleshooting-proxy-issues.mdx
When pasted into a real app (Express v5), this example would produce a TypeScript error. So I wrapped response.send(…) thing in {} to fix it.
> Don't return response.send from RequestHandler

- docs/reference/configuration.mdx
- docs/reference/error-codes.mdx
- source/memory-store.ts
- source/rate-limit.ts
- source/validations.ts
- test/library/validation-test.ts
This is mainly to catch values over node.js's maximum (~28.4 days), but it will also catch other invalid values such as negative numbers and NaN.
Fixes #546 (Sort of. It at least clarifies things - it's about as much of a fix as we're going to do.)
> Document windowMs limit for MemoryStore and warn on invalid values

- docs/guides/troubleshooting-proxy-issues.mdx
- docs/reference/changelog.mdx
- docs/reference/configuration.mdx
- docs/reference/error-codes.mdx
- source/rate-limit.ts
- source/validations.ts
- test/library/validation-test.ts
This alerts the user if a `Forwarded` header (standardized version of `X-Forwarded-For` & friends) is set when using the default `keyGenerator`, similar to our check for `X-Forwarded-For` when `trust proxy` is not enabled.
I also added an example to the docs with a custom `keyGenerator` that uses the [forwarded-parse](https://www.npmjs.com/package/forwarded-parse) library to parse and use the rightmost forwarded header (e.g. the last one, from the nearest proxy server).
This doesn't quite fix https://github.com/express-rate-limit/express-rate-limit/issues/488 but it definitely improves the situation. 
I'm hoping that support will eventually be added to express, e.g. via [proxy-addr](https://github.com/jshttp/proxy-addr/issues/20). If it doesn't, I may consider adding built-in support to …
> Add validation check for Forwarded header
